services:
  contelizer-nginx:
    image: nginx:stable-alpine
    depends_on:
      - contelizer-php
    networks:
      - contelizer-project
    volumes:
      - ".docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"

  contelizer-php:
    build:
      context: .docker/
    volumes:
      - ".:/var/www/html"
    networks:
      - contelizer-project

networks:
  contelizer-project:
    external: true
